DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;
DROP SEQUENCE doc_seq;

CREATE TABLE UTILISATEUR (
	idUser INTEGER CONSTRAINT pk_utilisateur PRIMARY KEY,
	login VARCHAR2(30),
	password VARCHAR2(30),
	name VARCHAR2(30),
	bibliothecaire INTEGER DEFAULT 0
);

CREATE TABLE DOCUMENT (
	idDoc INTEGER CONSTRAINT pk_document PRIMARY KEY,
	title VARCHAR2(30),
	author VARCHAR2(30),
	description VARCHAR2(255)
);

CREATE SEQUENCE doc_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;